name: GitHub pages auto publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build
    - name: Pushing to nanndo54.github.io
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'dist'
        destination-github-username: 'nanndo54'
        destination-repository-name: 'nanndo54.github.io'
        user-email: nanndo54@outlook.com
        target-branch: main
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
